#ifndef NFS_H
#define NFS_H

enum nfsproc3_op {
    NFSPROC3_NULL = 0,
    NFSPROC_GETATTR = 1,
    NFSPROC_SETATTR = 2,
    NFSPROC_LOOKUP = 3,
    NFSPROC_ACCESS = 4,
    NFSPROC_READLINK = 5,
    NFSPROC_READ = 6,
    NFSPROC_WRITE = 7,
    NFSPROC_CREATE = 8,
    NFSPROC_MKDIR = 9,
    NFSPROC_SYMLINK = 10,
    NFSPROC_MKNOD = 11,
    NFSPROC_REMOVE = 12,
    NFSPROC_RMDIR = 13,
    NFSPROC_RENAME = 14,
    NFSPROC_LINK = 15,
    NFSPROC_READDIR = 16,
    NFSPROC_READDIRPLUS = 17,
    NFSPROC_FSSTAT = 18,
    NFSPROC_FSINFO = 19,
    NFSPROC_PATHCONF = 20,
    NFSPROC_COMMIT = 21,
};

#define NFSPROC3_NOOP 22

#endif
